// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/v1/event.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is the atomic unit of state mutation in KAIROS.
// Every state change is an Event, appended to the log.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique event ID (ULID - time-sortable, 16 bytes)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Causal dependencies: event IDs this event depends on.
	// Forms a DAG for causal ordering.
	CausalDeps []string `protobuf:"bytes,2,rep,name=causal_deps,json=causalDeps,proto3" json:"causal_deps,omitempty"`
	// Payload type URL for Any unpacking (e.g., "type.googleapis.com/kairos.v1.TextInsert")
	PayloadType string `protobuf:"bytes,3,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// Serialized payload (protobuf Any)
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Hybrid Logical Clock timestamp (nanoseconds since epoch + logical counter)
	HlcTimestamp int64 `protobuf:"varint,5,opt,name=hlc_timestamp,json=hlcTimestamp,proto3" json:"hlc_timestamp,omitempty"`
	// Originator identity (Ed25519 public key, base64)
	Originator string `protobuf:"bytes,6,opt,name=originator,proto3" json:"originator,omitempty"`
	// Signature over (id + causal_deps + payload + hlc_timestamp) by originator
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// Session this event belongs to
	SessionId string `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Replication group (room, document, channel)
	GroupId       string `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCausalDeps() []string {
	if x != nil {
		return x.CausalDeps
	}
	return nil
}

func (x *Event) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetHlcTimestamp() int64 {
	if x != nil {
		return x.HlcTimestamp
	}
	return 0
}

func (x *Event) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *Event) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// EventBatch for efficient transport
type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_api_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// Snapshot manifest for persistence
type SnapshotManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	HlcTimestamp  int64                  `protobuf:"varint,2,opt,name=hlc_timestamp,json=hlcTimestamp,proto3" json:"hlc_timestamp,omitempty"`
	EventCount    int64                  `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	EventIds      []string               `protobuf:"bytes,4,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`                                                           // Events included in snapshot
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom: CRDT state hashes, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotManifest) Reset() {
	*x = SnapshotManifest{}
	mi := &file_api_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotManifest) ProtoMessage() {}

func (x *SnapshotManifest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotManifest.ProtoReflect.Descriptor instead.
func (*SnapshotManifest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotManifest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotManifest) GetHlcTimestamp() int64 {
	if x != nil {
		return x.HlcTimestamp
	}
	return 0
}

func (x *SnapshotManifest) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *SnapshotManifest) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *SnapshotManifest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Hybrid Logical Clock
type HLC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      int64                  `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"` // Nanoseconds since epoch
	Logical       int64                  `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`                   // Logical counter
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`        // Originating node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLC) Reset() {
	*x = HLC{}
	mi := &file_api_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLC) ProtoMessage() {}

func (x *HLC) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLC.ProtoReflect.Descriptor instead.
func (*HLC) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *HLC) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *HLC) GetLogical() int64 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLC) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// CRDT operation types (extensible via payload_type)
type TextInsert struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DocId    string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Position int64                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Text     string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// RGA-specific: after_id for concurrent insert ordering
	AfterId       string `protobuf:"bytes,4,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInsert) Reset() {
	*x = TextInsert{}
	mi := &file_api_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInsert) ProtoMessage() {}

func (x *TextInsert) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInsert.ProtoReflect.Descriptor instead.
func (*TextInsert) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *TextInsert) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *TextInsert) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *TextInsert) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextInsert) GetAfterId() string {
	if x != nil {
		return x.AfterId
	}
	return ""
}

type TextDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Position      int64                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDelete) Reset() {
	*x = TextDelete{}
	mi := &file_api_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDelete) ProtoMessage() {}

func (x *TextDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDelete.ProtoReflect.Descriptor instead.
func (*TextDelete) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *TextDelete) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *TextDelete) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *TextDelete) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type MapSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // Any serialized value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapSet) Reset() {
	*x = MapSet{}
	mi := &file_api_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapSet) ProtoMessage() {}

func (x *MapSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapSet.ProtoReflect.Descriptor instead.
func (*MapSet) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *MapSet) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapSet) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapSet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MapDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDelete) Reset() {
	*x = MapDelete{}
	mi := &file_api_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDelete) ProtoMessage() {}

func (x *MapDelete) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDelete.ProtoReflect.Descriptor instead.
func (*MapDelete) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *MapDelete) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapDelete) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CounterIncrement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CounterId     string                 `protobuf:"bytes,1,opt,name=counter_id,json=counterId,proto3" json:"counter_id,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterIncrement) Reset() {
	*x = CounterIncrement{}
	mi := &file_api_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterIncrement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterIncrement) ProtoMessage() {}

func (x *CounterIncrement) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterIncrement.ProtoReflect.Descriptor instead.
func (*CounterIncrement) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *CounterIncrement) GetCounterId() string {
	if x != nil {
		return x.CounterId
	}
	return ""
}

func (x *CounterIncrement) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type RegisterSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegisterId    string                 `protobuf:"bytes,1,opt,name=register_id,json=registerId,proto3" json:"register_id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSet) Reset() {
	*x = RegisterSet{}
	mi := &file_api_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSet) ProtoMessage() {}

func (x *RegisterSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSet.ProtoReflect.Descriptor instead.
func (*RegisterSet) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterSet) GetRegisterId() string {
	if x != nil {
		return x.RegisterId
	}
	return ""
}

func (x *RegisterSet) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Sync protocol messages
type SyncRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PeerId  string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Known version vector for delta sync
	KnownVersions map[string]int64 `protobuf:"bytes,3,rep,name=known_versions,json=knownVersions,proto3" json:"known_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Or request full state
	FullState     bool `protobuf:"varint,4,opt,name=full_state,json=fullState,proto3" json:"full_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *SyncRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SyncRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SyncRequest) GetKnownVersions() map[string]int64 {
	if x != nil {
		return x.KnownVersions
	}
	return nil
}

func (x *SyncRequest) GetFullState() bool {
	if x != nil {
		return x.FullState
	}
	return false
}

type SyncResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Events  []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"` // Delta events
	// Full state snapshot if requested
	Snapshot      []byte           `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	VersionVector map[string]int64 `protobuf:"bytes,4,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *SyncResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SyncResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SyncResponse) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SyncResponse) GetVersionVector() map[string]int64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

// Presence
type PresenceUpdate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Cursor position for text
	Cursor *Cursor `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Selection range
	Selection *Selection `protobuf:"bytes,4,opt,name=selection,proto3" json:"selection,omitempty"`
	// Custom presence data (avatar, status, etc.)
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Online        bool              `protobuf:"varint,6,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_api_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *PresenceUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceUpdate) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PresenceUpdate) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *PresenceUpdate) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *PresenceUpdate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PresenceUpdate) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int64                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	AnchorId      string                 `protobuf:"bytes,2,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"` // RGA anchor for collaborative cursors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_api_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *Cursor) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Cursor) GetAnchorId() string {
	if x != nil {
		return x.AnchorId
	}
	return ""
}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	StartAnchor   string                 `protobuf:"bytes,3,opt,name=start_anchor,json=startAnchor,proto3" json:"start_anchor,omitempty"`
	EndAnchor     string                 `protobuf:"bytes,4,opt,name=end_anchor,json=endAnchor,proto3" json:"end_anchor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_api_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *Selection) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Selection) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Selection) GetStartAnchor() string {
	if x != nil {
		return x.StartAnchor
	}
	return ""
}

func (x *Selection) GetEndAnchor() string {
	if x != nil {
		return x.EndAnchor
	}
	return ""
}

var File_api_v1_event_proto protoreflect.FileDescriptor

const file_api_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/event.proto\x12\tkairos.v1\"\x92\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcausal_deps\x18\x02 \x03(\tR\n" +
	"causalDeps\x12!\n" +
	"\fpayload_type\x18\x03 \x01(\tR\vpayloadType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12#\n" +
	"\rhlc_timestamp\x18\x05 \x01(\x03R\fhlcTimestamp\x12\x1e\n" +
	"\n" +
	"originator\x18\x06 \x01(\tR\n" +
	"originator\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\"6\n" +
	"\n" +
	"EventBatch\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.kairos.v1.EventR\x06events\"\x9a\x02\n" +
	"\x10SnapshotManifest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12#\n" +
	"\rhlc_timestamp\x18\x02 \x01(\x03R\fhlcTimestamp\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\x03R\n" +
	"eventCount\x12\x1b\n" +
	"\tevent_ids\x18\x04 \x03(\tR\beventIds\x12E\n" +
	"\bmetadata\x18\x05 \x03(\v2).kairos.v1.SnapshotManifest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x03HLC\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x12\x18\n" +
	"\alogical\x18\x02 \x01(\x03R\alogical\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"n\n" +
	"\n" +
	"TextInsert\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x19\n" +
	"\bafter_id\x18\x04 \x01(\tR\aafterId\"W\n" +
	"\n" +
	"TextDelete\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x03R\bposition\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"G\n" +
	"\x06MapSet\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"4\n" +
	"\tMapDelete\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"G\n" +
	"\x10CounterIncrement\x12\x1d\n" +
	"\n" +
	"counter_id\x18\x01 \x01(\tR\tcounterId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\"D\n" +
	"\vRegisterSet\x12\x1f\n" +
	"\vregister_id\x18\x01 \x01(\tR\n" +
	"registerId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xf4\x01\n" +
	"\vSyncRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12P\n" +
	"\x0eknown_versions\x18\x03 \x03(\v2).kairos.v1.SyncRequest.KnownVersionsEntryR\rknownVersions\x12\x1d\n" +
	"\n" +
	"full_state\x18\x04 \x01(\bR\tfullState\x1a@\n" +
	"\x12KnownVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x84\x02\n" +
	"\fSyncResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12(\n" +
	"\x06events\x18\x02 \x03(\v2\x10.kairos.v1.EventR\x06events\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\fR\bsnapshot\x12Q\n" +
	"\x0eversion_vector\x18\x04 \x03(\v2*.kairos.v1.SyncResponse.VersionVectorEntryR\rversionVector\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xbd\x02\n" +
	"\x0ePresenceUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12)\n" +
	"\x06cursor\x18\x03 \x01(\v2\x11.kairos.v1.CursorR\x06cursor\x122\n" +
	"\tselection\x18\x04 \x01(\v2\x14.kairos.v1.SelectionR\tselection\x12C\n" +
	"\bmetadata\x18\x05 \x03(\v2'.kairos.v1.PresenceUpdate.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06online\x18\x06 \x01(\bR\x06online\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x06Cursor\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x03R\bposition\x12\x1b\n" +
	"\tanchor_id\x18\x02 \x01(\tR\banchorId\"u\n" +
	"\tSelection\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\x12!\n" +
	"\fstart_anchor\x18\x03 \x01(\tR\vstartAnchor\x12\x1d\n" +
	"\n" +
	"end_anchor\x18\x04 \x01(\tR\tendAnchorB\"Z github.com/supunhg/kairos/api/v1b\x06proto3"

var (
	file_api_v1_event_proto_rawDescOnce sync.Once
	file_api_v1_event_proto_rawDescData []byte
)

func file_api_v1_event_proto_rawDescGZIP() []byte {
	file_api_v1_event_proto_rawDescOnce.Do(func() {
		file_api_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_event_proto_rawDesc), len(file_api_v1_event_proto_rawDesc)))
	})
	return file_api_v1_event_proto_rawDescData
}

var file_api_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_v1_event_proto_goTypes = []any{
	(*Event)(nil),            // 0: kairos.v1.Event
	(*EventBatch)(nil),       // 1: kairos.v1.EventBatch
	(*SnapshotManifest)(nil), // 2: kairos.v1.SnapshotManifest
	(*HLC)(nil),              // 3: kairos.v1.HLC
	(*TextInsert)(nil),       // 4: kairos.v1.TextInsert
	(*TextDelete)(nil),       // 5: kairos.v1.TextDelete
	(*MapSet)(nil),           // 6: kairos.v1.MapSet
	(*MapDelete)(nil),        // 7: kairos.v1.MapDelete
	(*CounterIncrement)(nil), // 8: kairos.v1.CounterIncrement
	(*RegisterSet)(nil),      // 9: kairos.v1.RegisterSet
	(*SyncRequest)(nil),      // 10: kairos.v1.SyncRequest
	(*SyncResponse)(nil),     // 11: kairos.v1.SyncResponse
	(*PresenceUpdate)(nil),   // 12: kairos.v1.PresenceUpdate
	(*Cursor)(nil),           // 13: kairos.v1.Cursor
	(*Selection)(nil),        // 14: kairos.v1.Selection
	nil,                      // 15: kairos.v1.SnapshotManifest.MetadataEntry
	nil,                      // 16: kairos.v1.SyncRequest.KnownVersionsEntry
	nil,                      // 17: kairos.v1.SyncResponse.VersionVectorEntry
	nil,                      // 18: kairos.v1.PresenceUpdate.MetadataEntry
}
var file_api_v1_event_proto_depIdxs = []int32{
	0,  // 0: kairos.v1.EventBatch.events:type_name -> kairos.v1.Event
	15, // 1: kairos.v1.SnapshotManifest.metadata:type_name -> kairos.v1.SnapshotManifest.MetadataEntry
	16, // 2: kairos.v1.SyncRequest.known_versions:type_name -> kairos.v1.SyncRequest.KnownVersionsEntry
	0,  // 3: kairos.v1.SyncResponse.events:type_name -> kairos.v1.Event
	17, // 4: kairos.v1.SyncResponse.version_vector:type_name -> kairos.v1.SyncResponse.VersionVectorEntry
	13, // 5: kairos.v1.PresenceUpdate.cursor:type_name -> kairos.v1.Cursor
	14, // 6: kairos.v1.PresenceUpdate.selection:type_name -> kairos.v1.Selection
	18, // 7: kairos.v1.PresenceUpdate.metadata:type_name -> kairos.v1.PresenceUpdate.MetadataEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_event_proto_init() }
func file_api_v1_event_proto_init() {
	if File_api_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_event_proto_rawDesc), len(file_api_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_event_proto_goTypes,
		DependencyIndexes: file_api_v1_event_proto_depIdxs,
		MessageInfos:      file_api_v1_event_proto_msgTypes,
	}.Build()
	File_api_v1_event_proto = out.File
	file_api_v1_event_proto_goTypes = nil
	file_api_v1_event_proto_depIdxs = nil
}
